import React from 'react';

function ToolBoxBar(props) {
  return (
    <div className="tool-box" style={{ display: props.show ? 'flex' : 'none' }}>
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/reacthooks-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/postman-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/netlify-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/heroku-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/json-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/jwt-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/git-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/gitkraken-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/mongoose-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/mongodbcompass-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/axios-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/api-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/ajaxorange-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/HackerRank-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/leetcode-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/discord-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/nvm-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/codewithmosh-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/firefox-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/formik-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/handlebars-logo.jpg')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/kingslanduniversity-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/lodash-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/mdn-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/msoffice-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/p4merge-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/php-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/onenote-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/pug-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/slack-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/softwaredevcycle-logo.png')}
        alt=""
      />
      <img
        className="tool-box-logo"
        src={require('../assets/Technologies/logos/stackoverflow-logo.png')}
        alt=""
      />
    </div>
  );
}

export default ToolBoxBar;